#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : smartcols
Version  : 0.3.0
Release  : 7
URL      : https://github.com/ignatenkobrain/python-smartcols/archive/v0.3.0.tar.gz
Source0  : https://github.com/ignatenkobrain/python-smartcols/archive/v0.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: smartcols-python3
Requires: smartcols-license
Requires: smartcols-python
BuildRequires : Cython
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(smartcols)
BuildRequires : pytest-runner
BuildRequires : python3-dev
BuildRequires : setuptools

%description
python-smartcols
================
Python bindings for util-linux libsmartcols-library.

%package license
Summary: license components for the smartcols package.
Group: Default

%description license
license components for the smartcols package.


%package python
Summary: python components for the smartcols package.
Group: Default
Requires: smartcols-python3

%description python
python components for the smartcols package.


%package python3
Summary: python3 components for the smartcols package.
Group: Default
Requires: python3-core

%description python3
python3 components for the smartcols package.


%prep
%setup -q -n python-smartcols-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531424978
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/smartcols
cp COPYING %{buildroot}/usr/share/doc/smartcols/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/smartcols/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
